[build-system]
requires = ["setuptools>=61.0", "wheel", "torch"]
build-backend = "setuptools.build_meta"

[project]
name = "se3cnn"
version = "0.1.0"
authors = [{name = "Mario Geiger"}]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "scipy",
    "appdirs",
    "lie_learn @ git+https://github.com/AMLab-Amsterdam/lie_learn",
]

[tool.setuptools]
packages = {find = {include = ["se3cnn*"]}}
zip-safe = false

[tool.setuptools.package-data]
"*" = ["*.so", "*.pth", "*.cu", "*.cpp", "*.h"]
